Repository RocketChat/Rocket.Chat.Electron, pull requests merged in 2018-12, with the labels that each got.

#1025 [FIX] Remove dependencies related to the npm's event-stream incident
  yarn.lock
Labels: subj: security, type: urgent

#1026 [FIX] Add additional condition for option "Show on unread"
  src/scripts/events.js
Labels: feat: notifications, plat: windows, type: bug

#1030 [NEW] Add Japanese translation.
  src/i18n/lang/ja.i18n.json
Labels: feat: i18n, stat: ready to merge, type: enhancement

#1028 [FIX] The behavior of clicking links when running RocketChat with subdir.
  src/public/preload.js
Labels: feat: web view, type: bug

#995 [NEW] Automatic reload on error page
  src/public/loading-error.html
Labels: feat: web view, stat: ready to merge, type: new feature

#919 [NEW] Add "save image" to context menu
  src/i18n/lang/en.i18n.json
  src/public/lib/SpellCheck.js
Labels: feat: context menu, feat: web view, stat: ready to merge, type: new feature

#1036 [BREAK] Update dependencies
  package.json
  src/background.js
  src/background/windowState.js
  yarn.lock
Labels: subj: security, type: enhancement

#1045 [IMPROVE] Pages and preload script changes
  package.json
  src/app.js
  src/background.js
  src/background/aboutDialog.js
  src/background/autoUpdate.js
  src/background/screenshare.js
  src/background/screenshareDialog.js
  src/background/updateDialog.js
  src/background/updates.js
  src/branding/branding.js
  src/branding/branding.less
  src/i18n/lang/de_DE.i18n.json
  src/i18n/lang/en.i18n.json
  src/i18n/lang/fr.i18n.json
  src/i18n/lang/ja.i18n.json
  src/i18n/lang/pt-BR.i18n.json
  src/i18n/lang/ru.i18n.json
  src/preload.js
  src/preload/contextMenu.js
  src/preload/events.js
  src/preload/jitsi.js
  src/preload/links.js
  src/preload/notifications.js
  src/preload/sidebar.js
  src/preload/spellchecking.js
  src/public/about-dialog.html
  src/public/app.html
  src/public/helpers/context_menu.js
  src/public/images/error.jpg
  src/public/images/not-found.jpg
  src/public/jitsi-preload.js
  src/public/lib/SpellCheck.js
  src/public/loading-error.html
  src/public/preload.js
  src/public/screenshare-dialog.html
  src/public/screenshare.html
  src/public/update-dialog.html
  src/public/update.html
  src/scripts/events.js
  src/scripts/webview.js
  src/stylesheets/main.less
  src/stylesheets/pages/about.less
  src/stylesheets/pages/loading-error.less
  src/stylesheets/pages/screenshare.less
  src/stylesheets/pages/update.less
  tasks/build-app.js
  tasks/bundle.js
  tasks/utils.js
  yarn.lock
Labels: feat: spell checker, feat: web view, type: enhancement

#1044 [NEW] Support for MacBooks Touch Bar
  src/background/mainWindow.js
  src/i18n/lang/en.i18n.json
  src/i18n/lang/ru.i18n.json
  src/public/images/icon-bold.png
  src/public/images/icon-code.png
  src/public/images/icon-italic.png
  src/public/images/icon-multi-line.png
  src/public/images/icon-strike.png
  src/scripts/events.js
  src/scripts/touchBar.js
Labels: plat: osx, type: enhancement
