Repository RocketChat/Rocket.Chat.Electron, pull requests merged in 2019-09, with the labels that each got.

#1324 [CHORE] Update dependencies
  yarn.lock
Labels: type: chore

#1275 [FIX] Fix custom oauth login issue (against develop branch)
  src/scripts/webview.js
Labels: type: bug

#1325 [IMPROVE] Add console warning to self-XSS
  src/i18n/lang/en.i18n.json
  src/scripts/start.js
  src/scripts/webview.js
Labels: type: enhancement
