Repository RocketChat/Rocket.Chat.Electron, pull requests merged in 2019-10, with the labels that each got.

#1341 [CHORE] Update XSS warning
  src/i18n/lang/en.i18n.json
Labels: type: chore

#1342 [IMPROVE] Update dependencies
  .travis.yml
  README.md
  appveyor.yml
  package.json
  src/e2e/.eslintrc
  src/e2e/app.e2e.js
  src/e2e/utils.js
  src/errorHandling.js
  src/i18n/index.js
  src/main.js
  src/main/appData.js
  src/main/certificateStore.js
  src/main/deepLinks.js
  src/main/dialogs/about.js
  src/main/dialogs/screenshare.js
  src/main/dialogs/update.js
  src/main/dock.js
  src/main/icon.spec.js
  src/main/mainWindow/index.js
  src/main/mainWindow/state.js
  src/main/menus.js
  src/main/menus.spec.js
  src/main/notifications.spec.js
  src/main/systemIdleTime.js
  src/main/tray.js
  src/main/updates.js
  src/preload.js
  src/preload/contextMenu.js
  src/preload/jitsi.js
  src/preload/links.js
  src/preload/notifications.js
  src/preload/spellchecking.js
  src/preload/titleChange.js
  src/preload/userPresence.js
  src/scripts/events.js
  src/scripts/servers.js
  src/scripts/sidebar.js
  src/scripts/start.js
  src/scripts/touchBar.js
  src/scripts/webview.js
  tasks/e2e.js
  tasks/index.js
  yarn.lock
Labels: type: enhancement

#1312 [FIX] [IMPROVE] French translations
  src/i18n/lang/fr.i18n.json
Labels: feat: i18n, type: enhancement

#1343 [FIX] Reenable webviews
  src/main/mainWindow/index.js
Labels: type: bug

#1344 [IMPROVE] Update tasks and metadata
  .eslintrc
  .gitignore
  .travis.yml
  README.md
  appveyor.yml
  babel.config.js
  gulpfile.js
  package.json
  rollup.config.js
  src/main.js
  src/scripts/dummy.spec.js
  tasks/build.js
  tasks/bundle.js
  tasks/coverage-reporter.js
  tasks/coverage.js
  tasks/env.js
  tasks/icons.js
  tasks/index.js
  tasks/release.js
  tasks/start.js
  tasks/test.js
  yarn.lock
Labels: type: enhancement

#1346 [FIX] Revert Linux artifacts names
  electron-builder.json
Labels: feat: installer / update, plat: linux, type: bug

#1347 [FIX] MacOS build
  .travis.yml
  build/entitlements.mas.inherit.plist
  build/entitlements.mas.plist
  build/notarize.js
  electron-builder.json
  gulpfile.js
  package.json
  yarn.lock
Labels: feat: installer / update, plat: osx, type: bug

#1366 [FIX] Spellchecker setup
  src/preload/spellchecking.js
  yarn.lock
Labels: feat: spell checker, type: bug

#1365 [FIX] powerMonitor API usage
  src/preload/userPresence.js
Labels: feat: web view, type: bug
