Repository RocketChat/Rocket.Chat.Electron, pull requests merged in 2019-03, with the labels that each got.

#1123 [FIX] "Remind me (this update) later" button
  src/public/update-dialog.html
Labels: feat: installer / update, type: bug

#1124 [FIX] Away detection
  package.json
  src/background.js
  src/background/systemIdleTime.js
  src/preload.js
  src/preload/events.js
  src/preload/userPresence.js
  yarn.lock
Labels: type: bug

#1129 [FIX] Mac App Store startup issue
  src/background.js
  src/background/aboutDialog.js
  src/background/dialogs/about.js
  src/background/dialogs/screenshare.js
  src/background/dialogs/update.js
  src/background/mainWindow.js
  src/background/screenshareDialog.js
  src/background/updateDialog.js
  src/public/dialogs/about.html
  src/public/dialogs/screenshare.html
  src/public/dialogs/update.html
  src/stylesheets/dialogs/about.less
  src/stylesheets/dialogs/screenshare.less
  src/stylesheets/dialogs/update.less
  src/stylesheets/main.less
Labels: plat: osx, subj: mac app store, type: bug

#1130 [FIX] Reply notifications in MacOS
  src/preload/notifications.js
Labels: feat: notifications, plat: osx, type: bug

#1132 [FIX] Apply memoization to spell checking
  src/preload/spellchecking.js
Labels: feat: i18n, subj: performance, type: bug

#1133 [FIX] Re-enable download links
  src/preload/links.js
Labels: feat: web view, type: bug

#1140 [FIX] Preload scripts compatibility
  package.json
  src/preload/jitsi.js
  src/preload/links.js
  src/preload/rocketChat.js
  src/preload/titleChange.js
  src/preload/userPresence.js
Labels: feat: web view, type: bug

#1125 [FIX] Sidebar and badges
  .stylelintrc
  src/background/dock.js
  src/background/icon.js
  src/background/icon.spec.js
  src/background/tray.js
  src/preload/sidebar.js
  src/public/app.html
  src/scripts/events.js
  src/scripts/servers.js
  src/scripts/sidebar.js
  src/scripts/start.js
  src/scripts/webview.js
  src/stylesheets/pages/app.less
  src/stylesheets/pages/app/sidebar.less
  src/stylesheets/pages/app/webview.less
  src/stylesheets/variables.less
Labels: feat: sidebar / servers list, feat: tray icon / dock / taskbar, type: bug
