Repository RocketChat/Rocket.Chat.Electron, pull requests merged in 2020-02, with the labels that each got.

#1495 chore: Remove sinon
  package.json
  yarn.lock
Labels: type: chore

#1503 feat: Side-effects in sagas
  src/actions.js
  src/components/AboutDialog.js
  src/components/AddServerView.js
  src/components/App.js
  src/components/CertificatesProvider.js
  src/components/MainWindow.js
  src/components/MenuBar.js
  src/components/SagaMiddlewareProvider.js
  src/components/ServersProvider.js
  src/components/SpellCheckingProvider.js
  src/components/TrayIcon.js
  src/components/UpdatesProvider.js
  src/components/WebUiView/useWebviewContextMenu.js
  src/components/WebUiView/useWebviewNavigation.js
  src/components/WebUiView/useWebviewPreload.js
  src/hooks/useCorrectionsForMisspelling.js
  src/hooks/useMisspellingDetection.js
  src/hooks/useServerValidation.js
  src/icons.js
  src/icons.spec.js
  src/main.js
  src/reducers/checksForUpdatesOnStartup.js
  src/reducers/currentServerUrl.js
  src/reducers/doCheckForUpdatesOnStartup.js
  src/reducers/installedSpellCheckingDictionariesDirectoryPath.js
  src/reducers/isCheckingForUpdates.js
  src/reducers/isEachUpdatesSettingConfigurable.js
  src/reducers/isHunspellSpellCheckerUsed.js
  src/reducers/isUpdatingAllowed.js
  src/reducers/isUpdatingEnabled.js
  src/reducers/servers.js
  src/reducers/skippedUpdateVersion.js
  src/reducers/spellCheckingDictionaries.js
  src/reducers/updatesConfigurable.js
  src/reducers/updatesEnabled.js
  src/sagas/certificates.js
  src/sagas/deepLinks.js
  src/sagas/servers.js
  src/sagas/spellChecking.js
  src/sagas/updates.js
  src/services/certificates.js
  src/services/servers.js
  src/services/spellChecking.js
  src/services/updates.js
  src/storeAndEffects.js
Labels: type: enhancement

#1504 feat!: Styled components
  .editorconfig
  .stylelintrc
  README.md
  gulpfile.js
  package.json
  src/components/AboutDialog/index.js
  src/components/AboutDialog/styles.js
  src/components/AddServerView/index.js
  src/components/AddServerView/styles.js
  src/components/App.js
  src/components/LoadingErrorView.js
  src/components/MainWindow/index.js
  src/components/MainWindow/styles.js
  src/components/RocketChatLogo.js
  src/components/ScreenSharingDialog.js
  src/components/ScreenSharingDialog/index.js
  src/components/ScreenSharingDialog/styles.js
  src/components/ServerView.js
  src/components/ServersView/ServerPane.js
  src/components/ServersView/index.js
  src/components/ServersView/styles.js
  src/components/ServersView/useWebviewContextMenu.js
  src/components/ServersView/useWebviewFocus.js
  src/components/ServersView/useWebviewNavigation.js
  src/components/ServersView/useWebviewPreload.js
  src/components/SideBar.js
  src/components/SideBar/index.js
  src/components/SideBar/styles.js
  src/components/SideBar/useKeyboardShortcuts.js
  src/components/SideBar/useSorting.js
  src/components/UpdateDialog.js
  src/components/UpdateDialog/index.js
  src/components/UpdateDialog/styles.js
  src/components/WebUiView/index.js
  src/hooks/useDialog.js
  src/main.js
  src/preload/changes.js
  src/public/app.html
  src/public/images/logo-dark.svg
  src/public/images/logo.svg
  src/reducers/servers.js
  src/sagas/navigationEvents.js
  src/storeAndEffects.js
  src/stylesheets/dialogs/about.less
  src/stylesheets/dialogs/screen-sharing.less
  src/stylesheets/dialogs/update.less
  src/stylesheets/main.less
  src/stylesheets/pages/app.less
  src/stylesheets/pages/app/sidebar.less
  src/stylesheets/pages/app/webview.less
  src/stylesheets/pages/loading-error.less
  src/stylesheets/utils/loading.less
  src/stylesheets/variables.less
  yarn.lock
Labels: type: enhancement

#1484 fix: Add snap connection for camera
  electron-builder.json
Labels: plat: linux, subj: package .snap, type: bug

#1508 refactor: Touch bar
  .eslintrc
  src/actions.js
  src/components/ServersView/useWebviewPreload.js
  src/components/TouchBar.js
  src/components/TouchBar/Bar.js
  src/components/TouchBar/Button.js
  src/components/TouchBar/Group.js
  src/components/TouchBar/Label.js
  src/components/TouchBar/Popover.js
  src/components/TouchBar/Scrubber.js
  src/components/TouchBar/SegmentedControl.js
  src/components/TouchBar/Spacer.js
  src/components/TouchBar/index.js
  src/components/TouchBar/useElementRefValue.js
  src/components/TouchBar/useElementsRefValues.js
  src/preload.js
  src/preload/changes.js
  src/preload/events.js
  src/reducers/isMessageBoxFocused.js
  src/sagas/navigationEvents.js
  src/storeAndEffects.js
Labels: feat: touchbar, plat: osx, type: enhancement

#1511 feat: Select client certificate dialog
  src/actions.js
  src/components/AboutDialog/index.js
  src/components/App.js
  src/components/ScreenSharingDialog/index.js
  src/components/SelectClientCertificateDialog/index.js
  src/components/ServersView/ServerPane.js
  src/components/UpdateDialog/index.js
  src/i18n.js
  src/i18n/en.i18n.json
  src/reducers/newUpdateVersion.js
  src/reducers/openDialog.js
  src/sagas/navigationEvents.js
  src/storeAndEffects.js
Labels: subj: security, type: enhancement

#1512 feat: Menu bar as components
  package.json
  src/components/App.js
  src/components/MenuBar.js
  src/components/MenuBar/AppMenu.js
  src/components/MenuBar/EditMenu.js
  src/components/MenuBar/HelpMenu.js
  src/components/MenuBar/ViewMenu.js
  src/components/MenuBar/WindowMenu.js
  src/components/MenuBar/index.js
  src/components/SideBar/index.js
  src/components/TouchBar/MessageBoxFormattingButtons.js
  src/components/TouchBar/ServerSelectionPopover.js
  src/components/TouchBar/index.js
  src/components/electron/Menu.js
  src/components/electron/MenuItem.js
  src/components/electron/TouchBarBar.js
  src/components/electron/TouchBarButton.js
  src/components/electron/TouchBarGroup.js
  src/components/electron/TouchBarLabel.js
  src/components/electron/TouchBarPopover.js
  src/components/electron/TouchBarScrubber.js
  src/components/electron/TouchBarSegmentedControl.js
  src/components/electron/TouchBarSpacer.js
  src/hooks/useElementRefValue.js
  src/hooks/useElementsRefValues.js
  yarn.lock
Labels: feat: menu, feat: touchbar, type: enhancement

#1518 fix: Display tray icon balloon when main window is hidden
  src/components/TrayIcon.js
  src/i18n/en.i18n.json
Labels: feat: tray icon / dock / taskbar, plat: windows, type: bug

#1522 fix: Command line args handling on packaged apps
  src/components/App.js
  src/main.js
  src/sagas/deepLinks.js
Labels: type: bug

#1524 regression: Clean state bugs
  .travis.yml
  gulpfile.js
  src/components/App.js
  src/components/MainWindow/sagas.js
  src/components/MenuBar/WindowMenu.js
Labels: type: bug

#1525 fix: Bugs related to focused webContents
  package.json
  src/actions.js
  src/components/AboutDialog/index.js
  src/components/AboutDialog/styles.js
  src/components/AddServerView/index.js
  src/components/AddServerView/styles.js
  src/components/App.js
  src/components/FailureImage.js
  src/components/MainWindow/index.js
  src/components/MainWindow/sagas.js
  src/components/MenuBar/AppMenu.js
  src/components/MenuBar/EditMenu.js
  src/components/ServersView/ServerPane.js
  src/components/ServersView/index.js
  src/components/ServersView/styles.js
  src/components/ServersView/useWebviewNavigation.js
  src/components/ServersView/useWebviewPreload.js
  src/components/Shell/index.js
  src/components/Shell/styles.js
  src/components/SideBar/styles.js
  src/components/electron/WebViewComponent.js
  src/components/utils/ErrorCatcher.js
  src/components/utils/ReparentingContainer.js
  src/hooks/useElementsRefValues.js
  src/preload/changes.js
  src/public/images/not-found.jpg
  src/reducers/editFlags.js
  src/reducers/focusedWebContentsId.js
  src/reducers/index.js
  yarn.lock
Labels: feat: web view, type: bug
