Repository RocketChat/Rocket.Chat.Electron, pull requests merged in 2020-07, with the labels that each got.

#1650 chore: Jest
  .editorconfig
  .eslintrc
  electron-builder.json
  gulpfile.js
  jest.config.json
  package.json
  rollup.config.js
  src/i18n/de-DE.i18n.json
  src/i18n/en.i18n.json
  src/i18n/fr.i18n.json
  src/i18n/hu.i18n.json
  src/i18n/ja.i18n.json
  src/i18n/pl.i18n.json
  src/i18n/pt-BR.i18n.json
  src/i18n/ru.i18n.json
  src/i18n/tr-TR.i18n.json
  src/i18n/uk-UA.i18n.json
  src/i18n/zh-CN.i18n.json
  src/i18n/zh-TW.i18n.json
  src/icons.spec.js
  yarn.lock
Labels: type: chore

#1651 deps: Update third-party dependencies
  .eslintrc
  package.json
  src/components/AboutDialog/index.js
  src/components/AddServerView/index.js
  src/components/App.js
  src/components/SagaMiddlewareProvider.js
  src/components/ServersView/useWebviewNavigation.js
  src/components/SideBar/index.js
  src/components/TrayIcon.js
  src/preload/userPresence.js
  yarn.lock
Labels: type: enhancement

#1652 deps: Update Fuselage
  package.json
  src/components/AboutDialog/index.js
  src/components/Dialog/index.js
  src/components/ScreenSharingDialog/index.js
  src/components/SelectClientCertificateDialog/index.js
  src/components/ServersView/ServerPane.js
  src/components/UpdateDialog/index.js
  yarn.lock
Labels: type: chore

#1654 fix: Remove wrong entitlements on MAS builds
  build/entitlements.mas.plist
Labels: plat: osx, subj: mac app store, type: bug

#1662 fix: No notification when the avatar icon comes from a relative URL
  src/preload/notifications.js
Labels: feat: notifications, type: bug

#1671 chore: Replace Gulp with npm scripts
  .travis.yml
  appveyor.yml
  build/icon.icns
  build/icons/512x512.png
  build/update-icons.js
  gulpfile.js
  package.json
  rollup.config.js
  src/main/dev.js
  src/main/spellChecking.js
  yarn.lock
Labels: type: chore

#1675 perf: Notifications on main process
  package.json
  src/main/sagas/root.js
  src/main/sagas/utils.js
  src/main/ui/notifications.js
  src/preload.js
  src/preload/errors.js
  src/preload/notifications.js
  yarn.lock
Labels: feat: notifications, type: enhancement
